#!/usr/bin/env python3
from subprocess import Popen, PIPE
import os
import time

os.system("v4l2-ctl -c gamma=5")
os.system("v4l2-ctl -c brightness=128")
os.system("v4l2-ctl -c contrast=67")

video_device_pipe = Popen('v4l2-ctl --list-devices | grep -A1 OBS | tail -n 1 | sed -E \'s|\s*(/dev/video[0-9]+)|\\1|\'', shell=True, stdout=PIPE).stdout

video_device = video_device_pipe.read().decode('utf-8').replace("\n", "")
print("Video device: " + video_device)
if video_device_pipe.close() is not None:
    video_device="/dev/video0"
file="~/.gitpix/" + str(int(time.time())) + ".png"
camera_operator = Popen("fswebcam -r 1920x1080 -d " + video_device + " --png 9 " + file, shell=True)
camera_operator.communicate()
if (camera_operator.returncode > 0):
    Popen("fswebcam -r 1920x1080 -d /dev/video0 --png 9 " + file, shell=True)
